### PR TITLE
Added ability to specify default value in blade directive

### PR DESCRIPTION
**Pull request by pashamesh**
Added ability to specify default value in blade directive

### CODE REVIEW

**Comment by pashamesh** [comment]
ping

**Comment by denisdulici** [comment]
Thanks Pasha

**Comment by denisdulici** [comment]
Pasha, this change breaks the package for PHP 7.2 as it makes the second parameter as required:

https://github.com/akaunting/akaunting/issues/416

Can you please fix it?

**Comment by denisdulici** [comment]
@pashamesh Can you please check this asap? It's breaking the package.

**Comment by pashamesh** [comment]
@denisdulici will check shortly

**Comment by pashamesh** [comment]
@denisdulici please check https://github.com/akaunting/setting/pull/14

**Pull request merged**
