### PR TITLE
Fixed $app var for laravel 8

### PR DESCRIPTION
**Pull request by dacoto97**

### CODE REVIEW

**Comment by dacoto97** [comment]
Relates to #68

**Comment by denisdulici** [comment]
`$this->container` is available in Laravel > 6. However, this package is compatible with Laravel > 5.3 version so can you please check it?

**Comment by dacoto97** [comment]
Laravel 5.x version is no longer supported.
So it would be necessary to withdraw support for this version in order to support laravel 8.x and future versions.

**Comment by denisdulici** [comment]
Thanks but not going to make such a change just for a property rename.

**Comment by dacoto97** [comment]
### ⚠️  Library not compatible with laravel 8.x or higher. ⚠️
As the library cannot be updated, it is **discarded** for versions of laravel **8.x or higher**.

**Pull request closed without merging**
